# Generated by Django 3.0.1 on 2020-02-22 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='Год выпуска')),
                ('gearbox', models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], default=0, verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
